name: Manually deploy SLS Prod
on:
  workflow_dispatch:

jobs:
  deploy:
    name: deploy Lambda + API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci
    - name: serverless deploy
      uses: SuprGames/serverless-github-action@v1.77
      with:
        command: deploy
        args: --stage prod --verbose
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        SERVICE_ROOT: user_service
